name: Releases
on:
  push:
    branches: ["main"]
on: workflow_dispatch

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkouts repo
        uses: actions/checkout@v3

      - name: Conventional changelog action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          skip-on-empty: false
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build app
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: latest
        - run: npm ci
        - run: npm i -g typescript webpack-cli
        - run: npx webpack --config webpack.config.js
        - run: node --experimental-sea-config sea-config.json
        - run: cp $(command -v node) server
        - run: npx postject server NODE_SEA_BLOB sea-prep.blob --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2
        

      - name: Create release
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          token: ${{ secrets.CHANGELOG_SECRET }}
          tag: ${{ steps.changelog.outputs.tag }}
          name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
